FROM python:3.9
WORKDIR /app
ENV PYTHONPATH "${PYTHONPATH}:/app/"
ENV PATH="${PATH}:/root/.local/bin"

RUN apt update && apt -y upgrade && apt install -y python3-setuptools netcat && pip install pipenv

COPY . .
RUN pipenv install --system --deploy --skip-lock
CMD ["celery", "-A", "core.celery_app", "beat"]
