version: '3.8'

services:

  payment_api:
    extends:
      file: docker-compose.yaml
      service: payment_api
    ports:
      - "8000:8000"
    env_file:
      - test.env

  subscription_api:
    extends:
      file: docker-compose.yaml
      service: subscription_api
    ports:
      - "8001:8001"
    env_file:
      - test.env

  admin:
    extends:
      service: admin
      file: docker-compose.yaml
    ports:
      - "8002:8002"
    env_file:
      - test.env

  postgres-tests:
    build: ./db
    networks:
      - movies-api-network
    restart: on-failure
    volumes:
      - postgresdata_test:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file:
      - test.env

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
    volumes:
      - redis_data_test:/opt/app/redis/data
    networks:
      - movies-api-network
    restart: on-failure

  rabbit:
    extends:
      file: docker-compose.yaml
      service: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  order_scheduler:
    extends:
      file: docker-compose.yaml
      service: order_scheduler
    env_file:
      - test.env

  order_worker:
    extends:
      file: docker-compose.yaml
      service: order_worker
    env_file:
      - test.env

  payment_scheduler:
    extends:
      file: docker-compose.yaml
      service: payment_scheduler
    env_file:
      - test.env

  payment_worker:
    extends:
      file: docker-compose.yaml
      service: payment_worker
    env_file:
      - test.env

networks:
  movies-api-network:
    name: movies-api-network
    driver: bridge

volumes:
  postgresdata_test:
    name: postgresdata_test
  redis_data_test:
    name: redis_data_test