"""add product_id to payments

Revision ID: 1e3354d73817
Revises: 170c69279523
Create Date: 2021-10-18 01:00:57.194967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3354d73817'
down_revision = '170c69279523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('product_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'product_id')
    # ### end Alembic commands ###
