"""added customer field to payments

Revision ID: 39c2293d4412
Revises: 4bab04757f77
Create Date: 2021-10-16 01:12:59.466599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c2293d4412'
down_revision = '4bab04757f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invoice_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'invoice_id')
    # ### end Alembic commands ###
