"""rename provider customer id

Revision ID: 7b02219909c6
Revises: 1e3354d73817
Create Date: 2021-10-18 01:19:20.272539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b02219909c6'
down_revision = '1e3354d73817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('provider_customer_id', sa.String(), nullable=True))
    op.drop_column('customers', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'provider_customer_id')
    # ### end Alembic commands ###
